import { BarChart3, Bell, Bot, FileBarChart, LayoutDashboard, LogOut, PanelLeftClose, PanelLeftOpen, PiggyBank, ReceiptText, Search, Settings, Sparkles } from "lucide-react";
import { NavLink } from "react-router-dom";
import { motion } from "framer-motion";
import useAuth from "../../hooks/useAuth";

const primaryItems = [{ label: "Overview", to: "/app/dashboard", icon: LayoutDashboard }, { label: "Expenses", to: "/app/expenses", icon: ReceiptText }, { label: "Budget", to: "/app/budget", icon: PiggyBank }];
const insightItems = [{ label: "Analytics", to: "/app/analytics", icon: BarChart3 }, { label: "Reports", to: "/app/reports", icon: FileBarChart }, { label: "AI Assistant", to: "/app/ai-assistant", icon: Bot }];

const Sidebar = ({ collapsed = false, onToggle, onNavigate }) => {
  const { logout } = useAuth();
  const renderItem = ({ label, to, icon: Icon }) => <NavLink key={to} to={to} onClick={onNavigate} title={collapsed ? label : undefined}>{({ isActive }) => <motion.div whileHover={{ x: collapsed ? 0 : 3 }} className={`group relative flex items-center gap-3 rounded-2xl px-3 py-3 text-sm font-medium transition ${isActive ? "bg-cyan-400/12 text-cyan-200" : "text-slate-400 hover:bg-slate-800/70 hover:text-slate-100"}`}><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl transition ${isActive ? "bg-cyan-400 text-slate-950 shadow-lg shadow-cyan-500/20" : "bg-slate-800 text-slate-400 group-hover:text-cyan-300"}`}><Icon size={18} /></span>{!collapsed && <><span className="min-w-0 flex-1 truncate">{label}</span>{isActive && <motion.span layoutId="sidebar-active" className="h-1.5 w-1.5 rounded-full bg-cyan-300" />}</>}</motion.div>}</NavLink>;
  return <aside className={`flex h-full flex-col rounded-3xl border border-slate-700/60 bg-[#111827]/90 p-3 shadow-2xl shadow-black/15 backdrop-blur-xl transition-all duration-300 ${collapsed ? "lg:p-3" : "lg:p-4"}`}>
    <div className={`flex items-center ${collapsed ? "justify-center" : "justify-between"} gap-2 px-2 py-2`}><NavLink to="/app/dashboard" onClick={onNavigate} className="flex min-w-0 items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-cyan-400 to-blue-600 shadow-lg shadow-cyan-500/20"><Sparkles size={20} /></span>{!collapsed && <span className="min-w-0"><strong className="block truncate text-sm tracking-wide text-white">FinanceFlow</strong><span className="block text-[10px] font-semibold uppercase tracking-[0.16em] text-cyan-300">Finance OS</span></span>}</NavLink>{onToggle && <button aria-label={collapsed ? "Expand sidebar" : "Collapse sidebar"} onClick={onToggle} className="hidden rounded-xl p-2 text-slate-400 transition hover:bg-slate-800 hover:text-white lg:block">{collapsed ? <PanelLeftOpen size={18} /> : <PanelLeftClose size={18} />}</button>}</div>
    {!collapsed && <div className="mx-2 mt-5 rounded-2xl border border-cyan-400/15 bg-cyan-400/[0.04] p-3 text-xs leading-5 text-slate-400"><Sparkles size={14} className="mb-2 text-cyan-300" />Your financial command center.</div>}
    <nav aria-label="Main navigation" className="mt-6 space-y-6"><div><p className={`mb-2 px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500 ${collapsed ? "sr-only" : ""}`}>Workspace</p><div className="space-y-1">{primaryItems.map(renderItem)}</div></div><div><p className={`mb-2 px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500 ${collapsed ? "sr-only" : ""}`}>Intelligence</p><div className="space-y-1">{insightItems.map(renderItem)}</div></div><div><p className={`mb-2 px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500 ${collapsed ? "sr-only" : ""}`}>Account</p><div className="space-y-1">{renderItem({ label: "Notifications", to: "/app/notifications", icon: Bell })}{renderItem({ label: "Settings", to: "/app/settings", icon: Settings })}</div></div></nav>
    <div className="mt-auto border-t border-slate-700/60 pt-3"><NavLink to="/app/search" onClick={onNavigate} title={collapsed ? "Search" : undefined} className="mb-1 flex items-center gap-3 rounded-2xl px-3 py-3 text-sm text-slate-400 transition hover:bg-slate-800 hover:text-white"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-800"><Search size={18} /></span>{!collapsed && <span>Search <kbd className="ml-2 rounded bg-slate-700 px-1.5 py-0.5 text-[10px]">⌘ K</kbd></span>}</NavLink><button onClick={logout} title={collapsed ? "Sign out" : undefined} className="flex w-full items-center gap-3 rounded-2xl px-3 py-3 text-sm text-rose-300 transition hover:bg-rose-400/10"><span className="grid h-9 w-9 place-items-center rounded-xl bg-rose-400/10"><LogOut size={18} /></span>{!collapsed && "Sign out"}</button></div>
  </aside>;
};
export default Sidebar;
