import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, CheckCircle2, LoaderCircle, Mail, Wallet } from "lucide-react";
import toast from "react-hot-toast";
import api from "../services/api";

const ForgotPasswordPage = () => {
  const [email, setEmail] = useState(""); const [loading, setLoading] = useState(false); const [sent, setSent] = useState(false); const [error, setError] = useState("");
  const submit = async (event) => { event.preventDefault(); if (loading) return; if (!/^\S+@\S+\.\S+$/.test(email)) return setError("Enter a valid email address."); setLoading(true); setError(""); try { const { data } = await api.post("/auth/forgot-password", { email }); setSent(true); toast.success(data.message); } catch (requestError) { const message = requestError?.response?.data?.message || "Unable to request a reset link. Please try again."; setError(message); toast.error(message); } finally { setLoading(false); } };
  return <main className="min-h-screen bg-[#0B1120] px-5 py-10 text-white"><div className="mx-auto flex min-h-[80vh] max-w-md items-center"><section className="w-full rounded-3xl border border-slate-700/70 bg-[#131A2A]/90 p-7 shadow-2xl shadow-black/20 backdrop-blur-xl sm:p-9"><Link to="/login" className="inline-flex items-center gap-2 text-sm text-slate-400 transition hover:text-cyan-300"><ArrowLeft size={16} /> Back to sign in</Link><div className="mt-8 flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br from-cyan-400 to-blue-600"><Wallet size={23} /></span><div><p className="font-semibold">FinanceFlow</p><p className="text-sm text-slate-400">Account recovery</p></div></div>{sent ? <div className="mt-9 text-center"><CheckCircle2 className="mx-auto text-emerald-300" size={46} /><h1 className="mt-5 text-2xl font-bold">Check your inbox</h1><p className="mt-3 text-sm leading-6 text-slate-400">If an account exists for <span className="text-slate-200">{email}</span>, you’ll receive a reset link shortly. It expires in 15 minutes.</p><Link to="/login" className="mt-7 inline-flex items-center gap-2 rounded-2xl bg-cyan-400 px-5 py-3 text-sm font-semibold text-slate-950">Return to sign in <ArrowRight size={16} /></Link></div> : <><h1 className="mt-9 text-3xl font-bold">Reset your password</h1><p className="mt-3 text-sm leading-6 text-slate-400">Enter your email and we’ll send a secure reset link if your account is eligible.</p><form onSubmit={submit} className="mt-7"><label className="text-sm font-medium text-slate-300">Email address</label><div className="relative mt-2"><Mail size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" /><input autoComplete="email" value={email} onChange={(event) => {
  setEmail(event.target.value);
  if (error) setError("");
}} aria-invalid={Boolean(error)} className="w-full rounded-2xl border border-slate-700 bg-slate-900/60 py-3 pl-11 pr-4 text-white outline-none focus:border-cyan-400 focus:ring-2 focus:ring-cyan-400/15" placeholder="you@example.com" /></div>{error && <p className="mt-2 text-xs text-rose-300">{error}</p>}<button disabled={loading} className="mt-6 flex w-full items-center justify-center gap-2 rounded-2xl bg-cyan-400 py-3 font-semibold text-slate-950 transition hover:bg-cyan-300 disabled:opacity-60">{loading ? <><LoaderCircle size={17} className="animate-spin" /> Sending link…</> : <>Send reset link <ArrowRight size={17} /></>}</button></form></>}</section></div></main>;
};
export default ForgotPasswordPage;
