import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Bell, BrainCircuit, Check, ChevronLeft, Clock3, Info, LoaderCircle, Search, ShieldCheck, SlidersHorizontal, Trash2, X } from "lucide-react";
import { AnimatePresence, motion } from "framer-motion";
import { clearAllNotifications, deleteNotification, getNotifications, markNotificationAsRead } from "../services/notificationService";

const classify = (notification) => {
  const text = `${notification.title} ${notification.message}`.toLowerCase();
  if (text.includes("budget")) return "Budget";
  if (text.includes("ai") || text.includes("insight")) return "AI";
  if (text.includes("security") || text.includes("password") || text.includes("login")) return "Security";
  return "General";
};
const appearance = (notification) => ({ warning: [AlertTriangle, "text-amber-300", "bg-amber-400/10"], error: [AlertTriangle, "text-rose-300", "bg-rose-400/10"], success: [Check, "text-emerald-300", "bg-emerald-400/10"], info: [Info, "text-cyan-300", "bg-cyan-400/10"] }[notification.type] || [Bell, "text-slate-300", "bg-slate-400/10"]);
const relativeGroup = (date) => { const current = new Date(); const value = new Date(date); const diff = Math.floor((new Date(current.getFullYear(), current.getMonth(), current.getDate()) - new Date(value.getFullYear(), value.getMonth(), value.getDate())) / 86400000); return diff === 0 ? "Today" : diff === 1 ? "Yesterday" : "Earlier"; };
const time = (date) => new Date(date).toLocaleString([], { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" });

const NotificationCenterPage = () => {
  const [notifications, setNotifications] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [filter, setFilter] = useState("All"); const [search, setSearch] = useState(""); const [sort, setSort] = useState("newest"); const [selected, setSelected] = useState(null);
  const load = async () => { setLoading(true); setError(""); try { const data = await getNotifications(); setNotifications(data.notifications || []); } catch { setError("We couldn't load notifications. Please try again."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const markRead = async (id) => { try { await markNotificationAsRead(id); setNotifications((items) => items.map((item) => item._id === id ? { ...item, read: true } : item)); } catch { setError("Unable to update this notification."); } };
  const remove = async (id) => { try { await deleteNotification(id); setNotifications((items) => items.filter((item) => item._id !== id)); if (selected?._id === id) setSelected(null); } catch { setError("Unable to delete this notification."); } };
  const markAllRead = async () => { const unread = notifications.filter((item) => !item.read); try { await Promise.all(unread.map((item) => markNotificationAsRead(item._id))); setNotifications((items) => items.map((item) => ({ ...item, read: true }))); } catch { setError("Unable to mark all notifications as read."); } };
  const clearAll = async () => { try { await clearAllNotifications(); setNotifications([]); setSelected(null); } catch { setError("Unable to clear notifications."); } };
  const filtered = useMemo(() => notifications.filter((item) => { const category = classify(item); const matchesFilter = filter === "All" || (filter === "Unread" ? !item.read : category === filter); return matchesFilter && `${item.title} ${item.message}`.toLowerCase().includes(search.toLowerCase()); }).sort((a, b) => sort === "newest" ? new Date(b.createdAt) - new Date(a.createdAt) : new Date(a.createdAt) - new Date(b.createdAt)), [notifications, filter, search, sort]);
  const groups = ["Today", "Yesterday", "Earlier"].map((name) => [name, filtered.filter((item) => relativeGroup(item.createdAt) === name)]).filter(([, items]) => items.length);
  const unread = notifications.filter((item) => !item.read).length;
  return <main className="min-h-screen bg-[#0B1120] text-white"><div className="mx-auto max-w-6xl space-y-6 px-4 py-5 sm:px-6 sm:py-7 lg:px-8"><motion.header initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="relative overflow-hidden rounded-3xl border border-slate-700/50 bg-[#131A2A] p-5 sm:p-8"><div className="absolute -right-16 -top-20 h-52 w-52 rounded-full bg-cyan-400/10 blur-3xl" /><div className="relative flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-300">FinanceFlow updates</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Notification center</h1><p className="mt-3 text-sm leading-6 text-slate-400">Stay on top of your financial activity, alerts, and account updates.</p></div><div className="rounded-2xl bg-cyan-400/10 px-4 py-3"><p className="text-xs text-cyan-100">Unread notifications</p><p className="mt-1 text-2xl font-bold text-white">{unread}</p></div></div></motion.header>
    <section className="rounded-3xl border border-slate-700/50 bg-[#131A2A] p-4 sm:p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="relative min-w-0 flex-1"><Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search notifications" className="w-full rounded-2xl border border-slate-700 bg-slate-900/60 py-2.5 pl-10 pr-3 text-sm outline-none transition focus:border-cyan-400" /></div><div className="flex flex-wrap gap-2">{["All", "Unread", "Budget", "AI", "Security"].map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-xl px-3 py-2 text-xs font-medium transition ${filter === item ? "bg-cyan-400 text-slate-950" : "bg-slate-900/60 text-slate-400 hover:text-white"}`}>{item}</button>)}<div className="flex items-center rounded-xl bg-slate-900/60 px-2"><SlidersHorizontal size={15} className="text-slate-500" /><select value={sort} onChange={(event) => setSort(event.target.value)} className="bg-transparent px-2 py-2 text-xs text-slate-300 outline-none"><option value="newest">Newest</option><option value="oldest">Oldest</option></select></div></div></div></section>
    <section className="rounded-3xl border border-slate-700/50 bg-[#131A2A] p-4 sm:p-6"><div className="flex flex-col gap-3 border-b border-slate-700/50 pb-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-slate-400">{filtered.length} notification{filtered.length !== 1 ? "s" : ""}</p><div className="flex gap-2"><button onClick={markAllRead} disabled={!unread} className="rounded-xl border border-slate-700 px-3 py-2 text-xs font-medium text-slate-300 transition hover:border-cyan-400 disabled:cursor-not-allowed disabled:opacity-40">Mark all as read</button><button onClick={clearAll} disabled={!notifications.length} className="rounded-xl border border-rose-400/30 px-3 py-2 text-xs font-medium text-rose-300 transition hover:bg-rose-400/10 disabled:cursor-not-allowed disabled:opacity-40">Clear all</button></div></div>
      {loading ? <div className="space-y-3 pt-5">{[0, 1, 2].map((item) => <div key={item} className="h-28 animate-pulse rounded-3xl bg-slate-900/60" />)}</div> : error ? <div className="py-16 text-center"><AlertTriangle className="mx-auto text-rose-300" /><p className="mt-4 text-slate-300">{error}</p><button onClick={load} className="mt-4 rounded-xl bg-cyan-400 px-4 py-2 text-sm font-semibold text-slate-950">Try again</button></div> : !filtered.length ? <div className="py-16 text-center"><Bell className="mx-auto text-slate-600" size={38} /><h2 className="mt-4 font-semibold text-slate-200">No notifications found</h2><p className="mt-2 text-sm text-slate-500">Try a different filter or check back later.</p></div> : <div className="pt-5">{groups.map(([group, items]) => <section key={group} className="mb-7 last:mb-0"><h2 className="mb-3 text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">{group}</h2><div className="space-y-3"><AnimatePresence>{items.map((item) => { const [Icon, iconTone, iconSurface] = appearance(item); const category = classify(item); return <motion.article layout initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, x: 40 }} key={item._id} className={`rounded-3xl border p-4 transition hover:border-cyan-400/40 sm:p-5 ${item.read ? "border-slate-700/50 bg-slate-900/30" : "border-cyan-400/25 bg-cyan-400/[0.035]"}`}><div className="flex gap-3"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-2xl ${iconSurface}`}><Icon size={19} className={iconTone} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-slate-100">{item.title}</h3>{!item.read && <span className="h-2 w-2 rounded-full bg-cyan-300" />}<span className="rounded-full bg-slate-800 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide text-slate-400">{category}</span></div><p className="mt-2 text-sm leading-6 text-slate-400">{item.message}</p><p className="mt-3 flex items-center gap-1 text-xs text-slate-500"><Clock3 size={13} /> {time(item.createdAt)}</p></div><div className="flex shrink-0 flex-col gap-1">{!item.read && <button aria-label="Mark as read" onClick={() => markRead(item._id)} className="rounded-lg p-2 text-cyan-300 transition hover:bg-cyan-400/10"><Check size={17} /></button>}<button aria-label="Delete notification" onClick={() => remove(item._id)} className="rounded-lg p-2 text-rose-300 transition hover:bg-rose-400/10"><Trash2 size={17} /></button><button onClick={() => { setSelected(item); if (!item.read) markRead(item._id); }} className="text-xs text-cyan-300 hover:text-cyan-200">Details</button></div></div></motion.article>; })}</AnimatePresence></div></section>)}</div>}</section>
  </div><AnimatePresence>{selected && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 grid place-items-center bg-slate-950/70 p-4 backdrop-blur-sm"><motion.div initial={{ y: 12, scale: 0.98 }} animate={{ y: 0, scale: 1 }} className="w-full max-w-lg rounded-3xl border border-slate-700 bg-[#131A2A] p-6 shadow-2xl"><div className="flex justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-cyan-300">{classify(selected)} notification</p><h2 className="mt-2 text-xl font-bold">{selected.title}</h2></div><button onClick={() => setSelected(null)} className="rounded-xl p-2 text-slate-400 hover:bg-slate-800"><X size={19} /></button></div><p className="mt-5 leading-7 text-slate-300">{selected.message}</p><p className="mt-5 text-sm text-slate-500">{time(selected.createdAt)}</p></motion.div></motion.div>}</AnimatePresence></main>;
};

export default NotificationCenterPage;
