import { useMemo, useState } from "react";
import { BarChart3, CalendarRange, Download, FileSpreadsheet, FileText, PiggyBank, Wallet } from "lucide-react";
import { motion } from "framer-motion";
import CountUp from "react-countup";
import toast from "react-hot-toast";
import useFinance from "../hooks/useFinance";
import MonthlyLineChart from "../components/charts/MonthlyLineChart";
import CategoryPieChart from "../components/charts/CategoryPieChart";
import BudgetVsActualChart from "../components/charts/BudgetVsActualChart";
import { formatCurrency } from "../utils/formatters";

const periods = ["Daily", "Weekly", "Monthly", "Yearly", "Custom"];
const ReportsPage = () => {
  const { analytics, dashboard, snapshot, loading, exportReport } = useFinance(); const [period, setPeriod] = useState("Monthly"); const [from, setFrom] = useState(""); const [to, setTo] = useState("");
  const comparison = useMemo(() => [{ label: "This period", budget: Number(snapshot?.monthlyBudget ?? dashboard?.monthlyBudget ?? 0), actual: Number(snapshot?.spent ?? dashboard?.totalExpenses ?? 0) }], [snapshot, dashboard]);
  const summary = [{ label: "Income", value: dashboard?.totalIncome ?? analytics?.totals?.totalIncome ?? 0, icon: Wallet, tone: "text-emerald-300", surface: "bg-emerald-400/10" }, { label: "Expenses", value: dashboard?.totalExpenses ?? analytics?.totals?.totalExpenses ?? 0, icon: BarChart3, tone: "text-rose-300", surface: "bg-rose-400/10" }, { label: "Savings", value: dashboard?.balance ?? analytics?.totals?.savings ?? 0, icon: PiggyBank, tone: "text-cyan-300", surface: "bg-cyan-400/10" }, { label: "Net balance", value: dashboard?.balance ?? 0, icon: Wallet, tone: "text-violet-300", surface: "bg-violet-400/10" }];
  const exportExcel = () => toast("Excel export is ready for backend integration.", { icon: "ℹ️" });
  return <main className="min-h-screen bg-[#0B1120] text-white"><div className="mx-auto max-w-7xl space-y-6 px-4 py-5 sm:px-6 sm:py-7 lg:px-8"><motion.header initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="relative overflow-hidden rounded-3xl border border-slate-700/50 bg-[#131A2A] p-5 shadow-2xl shadow-black/10 sm:p-8"><div className="absolute -right-16 -top-20 h-56 w-56 rounded-full bg-cyan-400/10 blur-3xl" /><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-300">Financial reporting</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Reports & exports</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Turn your financial activity into a clear, shareable view of income, spending, and savings.</p></div><div className="flex flex-wrap gap-2"><button onClick={() => exportReport("csv")} className="inline-flex min-h-11 items-center gap-2 rounded-2xl border border-slate-600 bg-slate-900/60 px-4 text-sm font-semibold text-slate-200 transition hover:border-cyan-400"><FileSpreadsheet size={17} /> CSV</button><button onClick={() => exportReport("pdf")} className="inline-flex min-h-11 items-center gap-2 rounded-2xl bg-cyan-400 px-4 text-sm font-semibold text-slate-950 transition hover:bg-cyan-300"><FileText size={17} /> PDF</button><button onClick={exportExcel} className="inline-flex min-h-11 items-center gap-2 rounded-2xl border border-slate-600 px-4 text-sm font-semibold text-slate-300 transition hover:border-cyan-400"><Download size={17} /> Excel</button></div></div></motion.header>
    <section className="rounded-3xl border border-slate-700/50 bg-[#131A2A] p-4 sm:p-5"><div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div className="flex flex-wrap gap-2">{periods.map((item) => <button key={item} onClick={() => setPeriod(item)} className={`rounded-xl px-3 py-2 text-xs font-medium transition ${period === item ? "bg-cyan-400 text-slate-950" : "bg-slate-900/60 text-slate-400 hover:text-white"}`}>{item}</button>)}</div>{period === "Custom" && <div className="flex flex-wrap items-center gap-2"><CalendarRange size={17} className="text-slate-500" /><input type="date" value={from} onChange={(event) => setFrom(event.target.value)} className="rounded-xl bg-slate-900 px-3 py-2 text-xs [color-scheme:dark]" /><span className="text-slate-500">to</span><input type="date" value={to} onChange={(event) => setTo(event.target.value)} className="rounded-xl bg-slate-900 px-3 py-2 text-xs [color-scheme:dark]" /></div>}<p className="text-xs text-slate-500">Preview: {period.toLowerCase()} reporting data</p></div></section>
    {loading ? <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{[0, 1, 2, 3].map((item) => <div key={item} className="h-36 animate-pulse rounded-3xl bg-[#131A2A]" />)}</div> : <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{summary.map((item, index) => { const Icon = item.icon; return <motion.article key={item.label} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.05 }} whileHover={{ y: -4 }} className="rounded-3xl border border-slate-700/50 bg-[#131A2A] p-5"><div className="flex justify-between"><div><p className="text-sm text-slate-400">{item.label}</p><p className="mt-3 text-2xl font-bold"><CountUp end={Number(item.value)} formattingFn={formatCurrency} /></p></div><span className={`grid h-11 w-11 place-items-center rounded-2xl ${item.surface}`}><Icon size={21} className={item.tone} /></span></div><p className="mt-4 text-xs text-slate-500">Current reporting preview</p></motion.article>; })}</section>}
    {!loading && !analytics ? <section className="rounded-3xl border border-dashed border-slate-700 bg-[#131A2A] py-20 text-center"><BarChart3 className="mx-auto text-slate-600" size={42} /><h2 className="mt-4 text-xl font-semibold">No report data yet</h2><p className="mt-2 text-sm text-slate-500">Add income and expenses to create your first report.</p></section> : <><section className="grid grid-cols-1 gap-6 xl:grid-cols-5"><div className="xl:col-span-3"><MonthlyLineChart data={analytics?.monthlyExpenses || []} /></div><div className="xl:col-span-2"><CategoryPieChart data={analytics?.categoryData || []} /></div></section><section className="grid grid-cols-1 gap-6 xl:grid-cols-5"><div className="xl:col-span-3"><BudgetVsActualChart data={comparison} /></div><section className="rounded-3xl border border-slate-700/50 bg-[#131A2A] p-5 sm:p-7 xl:col-span-2"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-cyan-300">Report preview</p><h2 className="mt-2 text-xl font-bold">Ready to share</h2><p className="mt-3 text-sm leading-6 text-slate-400">Your export includes recorded expenses, category context, and available AI insights. Choose CSV for spreadsheet analysis or PDF for a polished snapshot.</p><div className="mt-6 space-y-3"><div className="rounded-2xl bg-slate-900/55 p-4 text-sm"><span className="text-slate-500">Report period</span><p className="mt-1 font-semibold">{period}{period === "Custom" && (from || to) ? ` · ${from || "Start"} to ${to || "Today"}` : ""}</p></div><div className="rounded-2xl bg-slate-900/55 p-4 text-sm"><span className="text-slate-500">Expense records</span><p className="mt-1 font-semibold">{analytics?.categoryData?.length || 0} active categories</p></div></div></section></section></>}</div></main>;
};
export default ReportsPage;
