import { useEffect, useState } from "react";
import { Command, Search, Sparkles, X } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { useNavigate } from "react-router-dom";

const recentKey = "financeflow_recent_searches";
const GlobalSearchDialog = ({ open, onClose }) => {
  const navigate = useNavigate(); const [query, setQuery] = useState(""); const [recent, setRecent] = useState([]);
  useEffect(() => { if (open) { setRecent(JSON.parse(localStorage.getItem(recentKey) || "[]")); setQuery(""); } }, [open]);
  const submit = (term = query) => { const value = term.trim(); if (value) { const next = [value, ...recent.filter((item) => item !== value)].slice(0, 5); localStorage.setItem(recentKey, JSON.stringify(next)); } navigate(`/app/search${value ? `?q=${encodeURIComponent(value)}` : ""}`); onClose(); };
  return <AnimatePresence>{open && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[70] bg-slate-950/70 p-4 backdrop-blur-sm" onMouseDown={onClose}><motion.section initial={{ y: -16, scale: 0.98 }} animate={{ y: 24, scale: 1 }} exit={{ y: -16, scale: 0.98 }} onMouseDown={(event) => event.stopPropagation()} className="mx-auto w-full max-w-2xl overflow-hidden rounded-3xl border border-slate-700 bg-[#131A2A] shadow-2xl"><div className="flex items-center gap-3 border-b border-slate-700/50 p-4"><Search className="text-cyan-300" size={20} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") submit(); if (event.key === "Escape") onClose(); }} placeholder="Search FinanceFlow..." className="min-w-0 flex-1 bg-transparent text-sm text-white outline-none placeholder:text-slate-500" /><button onClick={onClose} className="rounded-xl p-2 text-slate-400 hover:bg-slate-800"><X size={18} /></button></div><div className="p-4"><button onClick={() => submit()} className="flex w-full items-center gap-3 rounded-2xl bg-cyan-400/10 p-4 text-left transition hover:bg-cyan-400/15"><span className="grid h-9 w-9 place-items-center rounded-xl bg-cyan-400 text-slate-950"><Command size={17} /></span><span><span className="block text-sm font-semibold text-white">Search everything</span><span className="block text-xs text-slate-400">Transactions, budgets, analytics, insights, notifications, and settings</span></span></button><p className="mt-5 text-[11px] font-semibold uppercase tracking-[0.15em] text-slate-500">Recent searches</p><div className="mt-2 flex flex-wrap gap-2">{recent.length ? recent.map((item) => <button key={item} onClick={() => submit(item)} className="rounded-xl bg-slate-900 px-3 py-2 text-xs text-slate-300 transition hover:text-cyan-300">{item}</button>) : <span className="text-xs text-slate-500">No recent searches yet.</span>}</div><p className="mt-5 text-[11px] font-semibold uppercase tracking-[0.15em] text-slate-500">Popular</p><div className="mt-2 flex flex-wrap gap-2">{["This month's spending", "Budget progress", "Savings tips"].map((item) => <button key={item} onClick={() => submit(item)} className="inline-flex items-center gap-1 rounded-xl bg-slate-900 px-3 py-2 text-xs text-slate-300 transition hover:text-cyan-300"><Sparkles size={12} className="text-cyan-300" />{item}</button>)}</div></div></motion.section></motion.div>}</AnimatePresence>;
};
export default GlobalSearchDialog;
